name: Codecov workflow
on:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - 'go.*'
      - '.github/**'
      - 'codecov.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.go'
      - 'go.*'
      - '.github/**'
      - 'codecov.yml'
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ["1.18", "1.19", "1.20"]
    steps:
    - name: Checkout Code
      uses: actions/checkout@master

    - name: Run Tests
      run: |
        go test -v -race --coverprofile=coverage.coverprofile --covermode=atomic ./...
